#define ASPNET_STATE_OBJECT                                0
#define ASPNET_STATE_SERVICE_SESSIONS_ACTIVE               212
#define ASPNET_STATE_SERVICE_SESSIONS_ABANDONED            214
#define ASPNET_STATE_SERVICE_SESSIONS_TIMED_OUT            216
#define ASPNET_STATE_SERVICE_SESSIONS_TOTAL                218
